# Generated by Django 3.1.3 on 2020-12-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('useremail', models.EmailField(max_length=254)),
                ('phonenum', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateTimeField(blank=True)),
                ('password', models.CharField(max_length=1050)),
            ],
        ),
    ]
